//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Compras_Renglones = new HashSet<Compras_Renglones>();
        }
    
        public string CUIT_Proveedor { get; set; }
        public int Nro_Comprobante { get; set; }
        public short Tipo_Comprobante { get; set; }
        public string Punto_Venta_Comp { get; set; }
        public int Nro_Movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Porcentaje_Descuento { get; set; }
        public decimal Importe_Descuento { get; set; }
        public decimal Importe_IVA { get; set; }
        public decimal Importe_Total { get; set; }
        public bool Pagado { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras_Renglones> Compras_Renglones { get; set; }
        public virtual Tipo_Comprobante Tipo_Comprobante1 { get; set; }
    }
}
