//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dias_atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dias_atencion()
        {
            this.Turnos_fijos = new HashSet<Turnos_fijos>();
        }
    
        public byte id_dia { get; set; }
        public string nombre_dia { get; set; }
        public Nullable<System.TimeSpan> hora_mañana { get; set; }
        public Nullable<System.TimeSpan> fin_hora_mañana { get; set; }
        public System.TimeSpan hora_tarde { get; set; }
        public System.TimeSpan fin_hora_tarde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos_fijos> Turnos_fijos { get; set; }
    }
}
