//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Compras_Renglones = new HashSet<Compras_Renglones>();
            this.Ventas_Lineas = new HashSet<Ventas_Lineas>();
        }
    
        public int Cod_Producto { get; set; }
        public int id_proveedor { get; set; }
        public int Cod_Marca { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public decimal Precio_Mayorista { get; set; }
        public int Stock { get; set; }
        public Nullable<short> Stock_minimo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras_Renglones> Compras_Renglones { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Lineas> Ventas_Lineas { get; set; }
    }
}
