//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int id_turno { get; set; }
        public int id_cliente { get; set; }
        public byte Nro_Empleado { get; set; }
        public byte Cod_Cancha { get; set; }
        public byte Tipo_turno { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public byte Estado { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado_Turno Estado_Turno { get; set; }
        public virtual Tipos_Turno Tipos_Turno { get; set; }
    }
}
